module softmax_unit #(
    parameter N         = 3,
    parameter FRAC      = 4,            // fractional bits of S_scaled (Q11.4)
    parameter LUT_DEPTH = 16,           // integer exp entries: e^0 .. e^-(LUT_DEPTH-1)
    parameter SUM_MAX   = N * 1024,
    parameter SUM_BITS  = $clog2(SUM_MAX + 1),
    parameter IDX_BITS  = $clog2(LUT_DEPTH)
)(
    input clk,
    input reset,
    input start,
    input  signed [31:0] S_scaled [0:N-1][0:N-1],  // Q27.4
    output reg    [15:0] A        [0:N-1][0:N-1],
    output reg done
);

    // e^-(i+f) = e^-i * e^-f, one Q1.10 x Q1.10 multiply between two LUTs.
    // All three ROMs are generated by scripts/gen_luts.py.
    reg [15:0] exp_int_lut  [0:LUT_DEPTH-1];
    reg [15:0] exp_frac_lut [0:(1<<FRAC)-1];
    reg [31:0] recip_lut    [0:SUM_MAX];

    initial begin
        $readmemh("data/exp_int_lut.txt",  exp_int_lut);
        $readmemh("data/exp_frac_lut.txt", exp_frac_lut);
        $readmemh("data/recip_lut.txt",    recip_lut);
    end

    localparam IDLE       = 3'd0;
    localparam FIND_MAX   = 3'd1;
    localparam CALC_EXP   = 3'd2;
    localparam CALC_SUM   = 3'd3;
    localparam NORMALIZE  = 3'd4;
    localparam NORM_STORE = 3'd5;
    localparam DONE_ST    = 3'd6;

    reg [2:0] state;

    // row/column counters are sized by N, not by the LUT depth
    localparam N_BITS = (N <= 1) ? 1 : $clog2(N);
    reg [N_BITS-1:0] exp_i,  exp_j;
    reg [N_BITS-1:0] norm_i, norm_j;

    reg signed [31:0]         row_max  [0:N-1];
    reg        [15:0]         exp_vals [0:N-1][0:N-1];
    reg        [SUM_BITS-1:0] row_sum  [0:N-1];

    reg signed [31:0]         row_max_comb [0:N-1];
    reg        [SUM_BITS-1:0] row_sum_comb [0:N-1];

    integer mi, mj;
    always @(*) begin
        for (mi = 0; mi < N; mi = mi + 1) begin
            row_max_comb[mi] = S_scaled[mi][0];
            row_sum_comb[mi] = exp_vals[mi][0];
            for (mj = 1; mj < N; mj = mj + 1) begin
                if (S_scaled[mi][mj] > row_max_comb[mi])
                    row_max_comb[mi] = S_scaled[mi][mj];
                row_sum_comb[mi] = row_sum_comb[mi] + exp_vals[mi][mj];
            end
        end
    end

    // exp of the current element: diff is Q11.4 and always <= 0 after the
    // max subtraction, so -diff splits into integer index i and fraction f.
    wire signed [31:0] diff         = S_scaled[exp_i][exp_j] - row_max[exp_i];
    wire        [31:0] neg_diff     = -diff;
    wire        [31-FRAC:0] int_raw = neg_diff[31:FRAC];
    wire [IDX_BITS-1:0] int_idx     = (int_raw >= LUT_DEPTH) ? LUT_DEPTH - 1
                                                             : int_raw[IDX_BITS-1:0];
    wire [FRAC-1:0]     frac_idx    = neg_diff[FRAC-1:0];
    // Q1.10 x Q1.10 -> Q.20; round back to Q1.10
    wire [31:0] exp_prod = exp_int_lut[int_idx] * exp_frac_lut[frac_idx];
    wire [15:0] exp_cur  = (exp_prod + (1 << 9)) >> 10;

    // normalize multiply: (e^d * 2^10) * (2^20 / sum) = prob * 2^20
    reg  [15:0] mul_a;
    reg  [31:0] mul_b;
    wire [47:0] mul_result = mul_a * mul_b;

    always @(posedge clk) begin
        if (reset) begin
            state  <= IDLE;
            done   <= 0;
            exp_i  <= 0;
            exp_j  <= 0;
            norm_i <= 0;
            norm_j <= 0;
            mul_a  <= 0;
            mul_b  <= 0;
        end else begin
            case (state)

                IDLE: begin
                    done <= 0;
                    if (start)
                        state <= FIND_MAX;
                end

                FIND_MAX: begin : find_max_blk
                    integer i;
                    for (i = 0; i < N; i = i + 1)
                        row_max[i] <= row_max_comb[i];
                    exp_i <= 0;
                    exp_j <= 0;
                    state <= CALC_EXP;
                end

                CALC_EXP: begin
                    exp_vals[exp_i][exp_j] <= exp_cur;

                    if (exp_j == N-1) begin
                        exp_j <= 0;
                        if (exp_i == N-1)
                            state <= CALC_SUM;
                        else
                            exp_i <= exp_i + 1;
                    end else begin
                        exp_j <= exp_j + 1;
                    end
                end

                CALC_SUM: begin : calc_sum_blk
                    integer i;
                    for (i = 0; i < N; i = i + 1)
                        row_sum[i] <= row_sum_comb[i];
                    norm_i <= 0;
                    norm_j <= 0;
                    state  <= NORMALIZE;
                end

                NORMALIZE: begin
                    mul_a <= exp_vals[norm_i][norm_j];
                    mul_b <= recip_lut[row_sum[norm_i]];
                    state <= NORM_STORE;
                end

                NORM_STORE: begin
                    // prob * 2^20 rounded down to prob * 2^8
                    A[norm_i][norm_j] <= (mul_result + (1 << 11)) >> 12;

                    if (norm_j == N-1) begin
                        norm_j <= 0;
                        if (norm_i == N-1) begin
                            state <= DONE_ST;
                        end else begin
                            norm_i <= norm_i + 1;
                            state  <= NORMALIZE;
                        end
                    end else begin
                        norm_j <= norm_j + 1;
                        state  <= NORMALIZE;
                    end
                end

                DONE_ST: begin
                    done  <= 1;
                    state <= IDLE;
                end

            endcase
        end
    end

endmodule
